
networks:
  privnet:
    driver: bridge

services:
  backend:
    image: boyeff/helloworld
    depends_on:
      - "postgresdb"
    build: 
      context: .
      dockerfile: API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - 8080:80
    networks:
      - privnet

  postgresdb:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "helloworld"
    networks:
      - privnet