version: '3.4'

services:
  helloworld-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - 8080:80
      - 8081:443
  
  helloworld-postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "helloworld"