version: '3.4'


networks:
  privnet:
    driver: bridge

services:
  helloworld-api:
    container_name: helloworld_api
    depends_on:
      - "helloworld-postgres"
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - privnet

  helloworld-postgres:
    container_name: helloworld_postgres
    image: postgres:latest
    command: postgres -c log_statement=all
    restart: always
    networks:
      - privnet

  integration-tests:
    container_name: testing_api
    depends_on:
      - helloworld-postgres
    build: 
      context: .
      dockerfile: Dockerfile
      target: integrationtestrunner
    networks:
      - privnet


      
