version: '3.4'

services:
  helloworld-api:
    container_name: helloworld_api
    depends_on:
      - "helloworld-postgres"
    build: 
      context: .
      dockerfile: Dockerfile

  helloworld-postgres:
    container_name: helloworld_postgres
    image: postgres:latest
    command: postgres -c log_statement=all
    restart: always

  integration-tests:
    profiles: ["tests"]
    container_name: testing_api
    depends_on:
      - helloworld-postgres
    build: 
      context: .
      dockerfile: Dockerfile
      target: integrationtestrunner


      
